version: '3'

services:
  web:
    build: ./wordpress
    image: gtctek/wordpress:latest
    container_name: fitdad-web
    hostname: fitdad-web
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/html
    depends_on:
      - mariadb
    networks:
      - dev-env
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: fitdad-phpmyadmin
    hostname: fitdad-phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - dev-env
  mariadb:
    image: mariadb:latest
    container_name: fitdad-mariadb
    hostname: fitdad-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'r00tp4ssw0rd'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'w0rdpr3ss'
      MYSQL_DATABASE: 'wordpress'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dev-env
volumes:
  mysqldata: {}
networks:
  dev-env: {}